services:
  - type: web
    name: stryd-shoe-store-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URLS
        sync: false
      - key: MONGODB_URI
        sync: false
