export const seedProducts = [
  {
    name: "Vayu Runner Pro",
    slug: "vayu-runner-pro",
    brand: "Campus",
    color: "Obsidian / White",
    category: "Running",
    price: 15999,
    badge: "NEW",
    rating: 4.8,
    reviewCount: 184,
    inventory: 18,
    sizes: [7, 8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=86",
    description: "A light knit runner with responsive cushioning and a grippy street-to-track outsole.",
    featured: true
  },
  {
    name: "Aangan Classic 85",
    slug: "aangan-classic-85",
    brand: "Campus",
    color: "Chalk / Gum",
    category: "Casual",
    price: 10999,
    rating: 4.6,
    reviewCount: 96,
    inventory: 24,
    sizes: [6, 7, 8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=1000&q=86",
    description: "A clean everyday court silhouette with soft lining and a durable gum sole.",
    featured: true
  },
  {
    name: "Gati X",
    slug: "gati-x",
    brand: "Sparx",
    color: "Signal Red",
    category: "Sport",
    price: 18999,
    oldPrice: 22999,
    badge: "SALE",
    rating: 4.7,
    reviewCount: 121,
    inventory: 9,
    sizes: [8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=86",
    description: "A fast training profile tuned for forward roll, stability, and explosive repeats.",
    featured: true
  },
  {
    name: "Parvat Boot",
    slug: "parvat-boot",
    brand: "Woodland",
    color: "Raw Tan",
    category: "Boots",
    price: 21999,
    rating: 4.9,
    reviewCount: 208,
    inventory: 12,
    sizes: [7, 8, 9, 10, 11, 12],
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=1000&q=86",
    description: "Weather-ready leather boots with firm ankle support and trail-grade traction.",
    featured: true
  },
  {
    name: "Chowk Low",
    slug: "chowk-low",
    brand: "Bata",
    color: "Triple Black",
    category: "Casual",
    price: 8999,
    rating: 4.4,
    reviewCount: 74,
    inventory: 32,
    sizes: [6, 7, 8, 9, 10],
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=1000&q=86",
    description: "A low-profile staple built for all-day wear, textured layers, and easy styling."
  },
  {
    name: "Jungle Blazer GTX",
    slug: "jungle-blazer-gtx",
    brand: "Liberty",
    color: "Forest / Earth",
    category: "Boots",
    price: 14999,
    badge: "NEW",
    rating: 4.5,
    reviewCount: 89,
    inventory: 15,
    sizes: [7, 8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=86",
    description: "A rugged outdoor shoe with reinforced overlays and water-resistant materials."
  },
  {
    name: "Raja Dress",
    slug: "raja-dress",
    brand: "Red Chief",
    color: "Cognac Leather",
    category: "Casual",
    price: 23999,
    rating: 4.7,
    reviewCount: 61,
    inventory: 7,
    sizes: [8, 9, 10, 11, 12],
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=1000&q=86",
    description: "Polished leather construction shaped for formal looks without sacrificing comfort."
  },
  {
    name: "Roznaa Trainer",
    slug: "roznaa-trainer",
    brand: "Khadim's",
    color: "Sky / Silver",
    category: "Running",
    price: 12499,
    oldPrice: 14999,
    badge: "SALE",
    rating: 4.6,
    reviewCount: 138,
    inventory: 22,
    sizes: [6, 7, 8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1000&q=86",
    description: "A dependable daily trainer with balanced foam and a secure midfoot lockdown."
  },
  {
    name: "Hawa Street 90",
    slug: "hawa-street-90",
    brand: "Campus",
    color: "Amber / Blue",
    category: "Sport",
    price: 13499,
    rating: 4.5,
    reviewCount: 117,
    inventory: 21,
    sizes: [7, 8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=1000&q=86",
    description: "A bold street sneaker with visible cushion geometry and sharp color blocking."
  },
  {
    name: "Saral Slipstream",
    slug: "saral-slipstream",
    brand: "Sparx",
    color: "Ivory / Black",
    category: "Casual",
    price: 11499,
    rating: 4.3,
    reviewCount: 52,
    inventory: 19,
    sizes: [6, 7, 8, 9, 10],
    image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=1000&q=86",
    description: "A minimal low-top with soft structure, padded heel, and everyday grip."
  },
  {
    name: "Nagar Hiker",
    slug: "nagar-hiker",
    brand: "Bata",
    color: "Stone / Moss",
    category: "Boots",
    price: 16999,
    oldPrice: 19999,
    badge: "SALE",
    rating: 4.8,
    reviewCount: 143,
    inventory: 11,
    sizes: [8, 9, 10, 11, 12],
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1000&q=86",
    description: "A city hiker with abrasion-resistant panels and a cushioned commute-ready base."
  },
  {
    name: "Maharaja Leather",
    slug: "maharaja-leather",
    brand: "Red Chief",
    color: "Black Leather",
    category: "Casual",
    price: 20999,
    rating: 4.9,
    reviewCount: 77,
    inventory: 10,
    sizes: [8, 9, 10, 11],
    image: "https://images.unsplash.com/photo-1610398752800-146f269dfcc8?auto=format&fit=crop&w=1000&q=86",
    description: "A premium leather profile for formal days, refined evenings, and sharp travel looks."
  }
];

export const testimonials = [
  {
    name: "Aarav Mehta",
    role: "Marathon runner",
    quote: "The running edit helped me compare cushion, price, and fit without opening five different pages.",
    rating: 5
  },
  {
    name: "Neha Saini",
    role: "Sneaker collector",
    quote: "Brand filtering is clean, fast, and the product cards show the details I actually care about.",
    rating: 5
  },
  {
    name: "Kabir Khan",
    role: "Retail buyer",
    quote: "The cart feels lightweight but complete. Quantity, subtotal, shipping copy, all in one place.",
    rating: 4
  }
];
